### ISSUE TITLE
Accepted aspect ratios not editable

### ISSUE THREAD

**Issue by Liquoriced** [RyanMelena/Jellyfin.Plugin.OriginalAspectRatio#2]
Settings is not retaining changes to "Accepted aspect ratios" field and reverts to defaults after saving.
It does save the other setting changes, but not the "Accepted aspect ratios".

![image](https://github.com/user-attachments/assets/fa2dae65-690a-4ba6-8d65-de11ebec4b1c)
![image](https://github.com/user-attachments/assets/20bd5591-e8b6-45bb-a0d6-44ebf25ff593)

**Comment by RyanMelena** [comment]
Thank you for the report, I believe I found the issue.  It should be corrected in release v1.0.2.  Please give it a try and let me know.

**Comment by Liquoriced** [comment]
It's fixed now - but how do we launch the scan of movies? I don't see any scheduled task for it.
BTW, the latest version that you published was flagged as containing a virus.

**Comment by RyanMelena** [comment]
Glad it is fixed.  The process runs as part of metadata retrieval.  If you want to run everything you should be able to kick it off using "Scan All Libraries" on the dashboard.  Depending on your hardware it can take a good bit of time to analyze each movie.  You can tell the process is working from log messages like...

```
Jellyfin.Plugin.OriginalAspectRatio.Providers.OriginalAspectRatioMetadataProvider: Performing ffmpeg cropdetect on "<file>" to determine original aspect ratio.
Jellyfin.Plugin.OriginalAspectRatio.Providers.OriginalAspectRatioMetadataProvider: Cropdetect found width of 3840 and height of 1600 for "<file>".
Jellyfin.Plugin.OriginalAspectRatio.Providers.OriginalAspectRatioMetadataProvider: Discovered original aspect ratio value of 2.4 for "<title>"
Jellyfin.Plugin.OriginalAspectRatio.Providers.OriginalAspectRatioMetadataProvider: Matched discovered original aspect ratio of 2.4 to accepted original aspect ratios value of "2.40" for "<title>".
Jellyfin.Plugin.OriginalAspectRatio.Providers.OriginalAspectRatioMetadataProvider: Accepted original aspect ratio of 2.40 for "<title>" matches video stream aspect ratio of 2.40, skipping.
```

I'll double-check the virus flag but the only things in the .zip should be the plugin .dll and metadata.json and the only change was the one documented in the changelog.
