### ISSUE TITLE
Scan Process Doesn't Start

### ISSUE THREAD

**Issue by Liquoriced** [RyanMelena/Jellyfin.Plugin.OriginalAspectRatio#3]
As shown in the attached log, the plugin is started but no aspect ratio scan is done when Scan All Libraries was launched at 15:37.
Also, as shown in the image below, the field Original Aspect Ratio in the metadata remains blank (I assume that's where it gets populated).

[log.txt](https://github.com/user-attachments/files/17995599/log.txt)

![image](https://github.com/user-attachments/assets/ae0b25d6-9d7c-4986-a556-5f018f2c68b5)

**Comment by RyanMelena** [comment]
I noticed this in the provided log:

`Emby.Server.Implementations.Plugins.PluginManager: Skipping disabled plugin "1.0.2.0" of "Original Aspect Ratio Detector" `

Can you confirm that the plugin is enabled.  I have occasionally had issues with the plugin being disabled after a manual upgrade.  In those cases I have had success with the following process:

1. Uninstall plugin via Jellyfin web UI
2. Restart Jellyfin
3. Re-install plugin
4. Restart Jellyfin
